version: '3'
services:
  bot:
    build: .
    image: pampyh0bizeps/nodejs-telegram-bot
    ports:
      - '5005:5005'
    container_name: 'nodejs-telegram-bot'
    depends_on:
      - redis
  redis:
    image: redis
    container_name: 'nodejs-bot-db'
